---
# Source: rancher/templates/issuer-rancher.yaml
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: rancher
  namespace: cattle-demo
  labels:
    app: rancher
    chart: rancher-2019.1.2
    heritage: Tiller
    release: rancher
spec:
  ca:
    secretName: tls-rancher

