---
# Source: rancher/templates/serviceAccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rancher
  namespace: cattle-demo
  labels:
    app: rancher
    chart: rancher-2019.1.2
    heritage: Tiller
    release: rancher

